version: '2'
services:
    api-service:
        build: ../.
        volumes:
          - "../src:/var/www/api/src"
          - "./pm2.json:/var/www/api/pm2.json"
          - "./nodemon.json:/var/www/api/nodemon.json"
          - './nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf'
        ports:
            - "81:80"
        environment:
            - "NODE_ENV=dev"
            - APP_PORT=3001
